# Generated by Django 4.0 on 2022-11-13 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eatery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Item', max_length=40)),
                ('base_price', models.FloatField(blank=True, null=True)),
                ('eatery', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='eatery.eatery')),
            ],
        ),
    ]
