# Generated by Django 4.0 on 2022-11-15 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='base_price',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
