from api.dfg.nodes.DfgNode import DfgNode
from api.dfg.nodes.macros.LeftMergeEvents import LeftMergeEvents


class LeftMergeRepeatedEvents(LeftMergeEvents):
    """
    Merges two lists of Event objects, one of which consists of a list of events generated by a
    repeated schedule and the other of which consists of a list of events that are exceptions
    """

    def __init__(self, left: DfgNode, right: DfgNode):
        super().__init__(left, right, ["canonical_date", "generated_by"])
