services:
  web:
    build: .
    env_file: .env
    volumes:
      - .:/src
  web_make_migrations:
    extends:
      service: web
    command: python manage.py makemigrations
  web_migrate:
    extends:
      service: web
    command: python manage.py migrate
  web_run:
    extends:
      service: web
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"