# Generated by Django 4.0 on 2022-09-14 15:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('eatery', '0001_initial'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepeatingEventSchedule',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('event_description', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Brunch', 'Brunch'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('General', 'General')], max_length=10)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('repeat_interval', models.IntegerField()),
                ('offset_lst', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('eatery', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='eatery.eaterystore')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleException',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('exception_type', models.CharField(choices=[('closed', 'Closed'), ('modified', 'Modified')], max_length=10)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('eatery', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='eatery.eaterystore')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.repeatingeventschedule')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='dateeventschedule',
            name='eatery',
        ),
        migrations.RemoveField(
            model_name='dateeventschedule',
            name='menu',
        ),
        migrations.AlterUniqueTogether(
            name='dayofweekeventschedule',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='dayofweekeventschedule',
            name='eatery',
        ),
        migrations.RemoveField(
            model_name='dayofweekeventschedule',
            name='menu',
        ),
        migrations.AlterField(
            model_name='alertstore',
            name='eatery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='eatery.eaterystore'),
        ),
        migrations.AlterField(
            model_name='itemstore',
            name='eatery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='eatery.eaterystore'),
        ),
        migrations.AlterField(
            model_name='menustore',
            name='eatery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='eatery.eaterystore'),
        ),
        migrations.AlterField(
            model_name='reportstore',
            name='eatery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='eatery.eaterystore'),
        ),
        migrations.AlterField(
            model_name='transactionhistorystore',
            name='eatery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='eatery.eaterystore'),
        ),
        migrations.DeleteModel(
            name='ClosedEventSchedule',
        ),
        migrations.DeleteModel(
            name='DateEventSchedule',
        ),
        migrations.DeleteModel(
            name='DayOfWeekEventSchedule',
        ),
        migrations.DeleteModel(
            name='EateryStore',
        ),
        migrations.AddField(
            model_name='repeatingeventschedule',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.menustore'),
        ),
        migrations.AlterUniqueTogether(
            name='repeatingeventschedule',
            unique_together={('eatery', 'event_description')},
        ),
    ]
