# Generated by Django 4.0 on 2023-04-13 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eatery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=250)),
                ('start_timestamp', models.IntegerField()),
                ('end_timestamp', models.IntegerField()),
                ('eatery', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='eatery.eatery')),
            ],
        ),
    ]
