# Generated by Django 4.0 on 2021-12-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('canonical_date', models.DateField()),
                ('start_timestamp', models.TimeField()),
                ('end_timestamp', models.TimeField()),
                ('transaction_count', models.IntegerField()),
            ],
        ),
    ]
