# Generated by Django 4.0 on 2023-04-22 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eatery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitTime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('wait_time_high', models.IntegerField()),
                ('wait_time_expected', models.IntegerField()),
                ('wait_time_low', models.IntegerField()),
                ('day', models.TextField(default=0)),
                ('hour', models.IntegerField(default=0)),
                ('trials', models.IntegerField(default=1)),
                ('eatery', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='wait_time', to='eatery.eatery')),
            ],
        ),
    ]
