# Generated by Django 4.0 on 2023-04-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Swipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('end_time', models.IntegerField()),
                ('session_type', models.CharField(max_length=40)),
                ('start_time', models.IntegerField()),
                ('swipe_density', models.FloatField()),
                ('wait_time_high', models.IntegerField()),
                ('wait_time_low', models.IntegerField()),
            ],
        ),
    ]
