# Generated by Django 4.0 on 2023-04-13 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eatery', '0001_initial'),
        ('swipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='swipe',
            name='eatery',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='swipe_data', to='eatery.eatery'),
            preserve_default=False,
        ),
    ]
