# Generated by Django 4.0 on 2023-04-19 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swipe', '0002_swipe_eatery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='swipe',
            old_name='end_time',
            new_name='canonical_date',
        ),
        migrations.RemoveField(
            model_name='swipe',
            name='session_type',
        ),
        migrations.RemoveField(
            model_name='swipe',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='swipe',
            name='swipe_density',
        ),
        migrations.RemoveField(
            model_name='swipe',
            name='wait_time_high',
        ),
        migrations.RemoveField(
            model_name='swipe',
            name='wait_time_low',
        ),
        migrations.CreateModel(
            name='WaitTime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('wait_time_high', models.IntegerField()),
                ('wait_time_expected', models.IntegerField()),
                ('wait_time_low', models.IntegerField()),
                ('timestamp', models.IntegerField()),
                ('swipe', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='data', to='swipe.swipe')),
            ],
        ),
    ]
