# Generated by Django 4.0 on 2022-01-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eateries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosedEventSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='categoryitemassociation',
            unique_together={('item', 'category')},
        ),
    ]
