# Generated by Django 4.0 on 2023-04-12 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eatery', '0003_alter_eatery_location_alter_eatery_menu_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('eatery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eatery.eatery')),
            ],
        ),
    ]
