# Generated by Django 4.0 on 2022-11-13 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20221109_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryitemassociation',
            name='category',
        ),
        migrations.RemoveField(
            model_name='categoryitemassociation',
            name='item',
        ),
        migrations.RemoveField(
            model_name='item',
            name='eatery',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='event',
        ),
        migrations.RemoveField(
            model_name='subitem',
            name='item',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='CategoryItemAssociation',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='SubItem',
        ),
    ]
