# Generated by Django 4.0 on 2023-04-05 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_remove_event_end_remove_event_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='start',
            field=models.IntegerField(default=0),
        ),
    ]
