# Generated by Django 4.0 on 2022-01-10 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eateries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_date', models.DateField()),
                ('block_end_time', models.TimeField()),
                ('transaction_count', models.IntegerField()),
                ('eatery', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='eateries.eaterystore')),
            ],
        ),
        migrations.AddIndex(
            model_name='transactionhistory',
            index=models.Index(fields=['canonical_date'], name='transaction_canonic_a40422_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='transactionhistory',
            unique_together={('eatery_id', 'block_end_time', 'canonical_date')},
        ),
    ]
