# Generated by Django 4.0 on 2021-12-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionhistory',
            old_name='end_timestamp',
            new_name='timestamp',
        ),
        migrations.AlterUniqueTogether(
            name='transactionhistory',
            unique_together={('name', 'timestamp', 'canonical_date')},
        ),
        migrations.AddIndex(
            model_name='transactionhistory',
            index=models.Index(fields=['name', 'timestamp', 'canonical_date'], name='transaction_name_204126_idx'),
        ),
        migrations.RemoveField(
            model_name='transactionhistory',
            name='start_timestamp',
        ),
    ]
