# Generated by Django 4.0 on 2021-12-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_rename_end_timestamp_transactionhistory_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transactionhistory',
            name='transaction_name_204126_idx',
        ),
        migrations.AddIndex(
            model_name='transactionhistory',
            index=models.Index(fields=['canonical_date'], name='transaction_canonic_a40422_idx'),
        ),
    ]
