# Generated by Django 4.0 on 2021-12-28 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_remove_transactionhistory_transaction_name_204126_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionhistory',
            old_name='timestamp',
            new_name='block_end_time',
        ),
        migrations.AlterUniqueTogether(
            name='transactionhistory',
            unique_together={('name', 'block_end_time', 'canonical_date')},
        ),
    ]
