# Generated by Django 4.0 on 2021-12-28 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_rename_timestamp_transactionhistory_block_end_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionhistory',
            old_name='block_end_time',
            new_name='bucket_end_time',
        ),
        migrations.AlterUniqueTogether(
            name='transactionhistory',
            unique_together={('name', 'bucket_end_time', 'canonical_date')},
        ),
    ]
