# Generated by Django 4.0 on 2021-12-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_rename_block_end_time_transactionhistory_bucket_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='bucket_end_time',
            field=models.IntegerField(),
        ),
    ]
