# Generated by Django 4.0 on 2021-12-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_alter_transactionhistory_bucket_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='bucket_end_time',
            field=models.TimeField(),
        ),
    ]
