# Generated by Django 4.0 on 2021-12-28 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_alter_transactionhistory_bucket_end_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionhistory',
            old_name='bucket_end_time',
            new_name='block_end_time',
        ),
        migrations.AlterUniqueTogether(
            name='transactionhistory',
            unique_together={('name', 'block_end_time', 'canonical_date')},
        ),
    ]
