# Generated by Django 4.0 on 2022-01-03 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_rename_bucket_end_time_transactionhistory_block_end_time_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transactionhistory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='eatery_id',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='transactionhistory',
            unique_together={('eatery_id', 'block_end_time', 'canonical_date')},
        ),
        migrations.RemoveField(
            model_name='transactionhistory',
            name='name',
        ),
    ]
