# Generated by Django 4.0 on 2022-01-10 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EateryStore',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=40)),
                ('menu_summary', models.CharField(blank=True, max_length=60)),
                ('image_url', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('campus_area', models.CharField(blank=True, choices=[('West', 'West'), ('North', 'North'), ('Central', 'Central'), ('Collegetown', 'Collegetown'), ('', 'None')], default='', max_length=15)),
                ('online_order', models.BooleanField(blank=True, null=True)),
                ('online_order_url', models.URLField(blank=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('payment_accepts_meal_swipes', models.BooleanField(blank=True, null=True)),
                ('payment_accepts_brbs', models.BooleanField(blank=True, null=True)),
                ('payment_accepts_cash', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('base_price', models.FloatField(blank=True, null=True)),
                ('eatery', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='eateries.eaterystore')),
            ],
        ),
        migrations.CreateModel(
            name='SubItemStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_price', models.FloatField(blank=True, null=True)),
                ('total_price', models.FloatField(blank=True, null=True)),
                ('name', models.CharField(max_length=40)),
                ('item_subsection', models.CharField(max_length=40)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='eateries.itemstore')),
            ],
        ),
        migrations.CreateModel(
            name='MenuStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('eatery', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='eateries.eaterystore')),
            ],
        ),
        migrations.CreateModel(
            name='ExceptionStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('start_timestamp', models.IntegerField()),
                ('end_timestamp', models.IntegerField()),
                ('eatery', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='eateries.eaterystore')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=40)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='eateries.menustore')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryItemAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='eateries.categorystore')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='eateries.itemstore')),
            ],
        ),
    ]
