# Generated by Django 4.0 on 2022-01-06 14:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EateryStore',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('menu_summary', models.CharField(max_length=60)),
                ('image_url', models.URLField()),
                ('location', models.CharField(max_length=30)),
                ('campus_area', models.CharField(choices=[('WST', 'West'), ('NRTH', 'North'), ('CNTRL', 'Central'), ('CTWN', 'Collegetown'), ('NN', '')], default='NN', max_length=5)),
                ('online_order', models.BooleanField(null=True)),
                ('online_order_url', models.URLField()),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('payment_accepts_meal_swipes', models.BooleanField(null=True)),
                ('payment_accepts_brbs', models.BooleanField(null=True)),
                ('payment_accepts_cash', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('eatery_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='eateries.eaterystore')),
            ],
        ),
        migrations.CreateModel(
            name='RepeatingEventSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3)),
                ('event_description', models.CharField(choices=[('BRKFST', 'Breakfast'), ('LNCH', 'Lunch'), ('DNNR', 'Dinner'), ('GNRL', 'General')], max_length=10)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('eatery_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='eateries.eaterystore')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='eateries.menustore')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItemStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=50)),
                ('price', models.FloatField(null=True)),
                ('eatery_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='eateries.eaterystore')),
            ],
        ),
        migrations.CreateModel(
            name='ForSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=40)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='eateries.menuitemstore')),
                ('menu_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='eateries.menustore')),
            ],
        ),
        migrations.CreateModel(
            name='ExceptionStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=80)),
                ('start_timestamp', models.DateTimeField()),
                ('end_timestamp', models.DateTimeField()),
                ('eatery_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='eateries.eaterystore')),
            ],
        ),
        migrations.CreateModel(
            name='EventChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('type', models.CharField(choices=[('INS', 'Insert'), ('DEL', 'Delete')], max_length=3)),
                ('event_description', models.CharField(choices=[('BRKFST', 'Breakfast'), ('LNCH', 'Lunch'), ('DNNR', 'Dinner'), ('GNRL', 'General')], max_length=10)),
                ('canonical_date', models.DateField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('eatery_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='eateries.eaterystore')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='eateries.menustore')),
            ],
        ),
        migrations.AddIndex(
            model_name='eventchangelog',
            index=models.Index(fields=['eatery_id', 'canonical_date'], name='eateries_ev_eatery__d34bcb_idx'),
        ),
        migrations.AddIndex(
            model_name='eventchangelog',
            index=models.Index(fields=['created_at'], name='eateries_ev_created_d237e2_idx'),
        ),
    ]
