# Generated by Django 4.0 on 2022-01-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eateries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eaterystore',
            name='campus_area',
            field=models.CharField(blank=True, choices=[('WST', 'West'), ('NRTH', 'North'), ('CNTRL', 'Central'), ('CTWN', 'Collegetown'), ('NN', '')], default='NN', max_length=5),
        ),
        migrations.AlterField(
            model_name='eaterystore',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='eaterystore',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eaterystore',
            name='location',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='eaterystore',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eaterystore',
            name='menu_summary',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='eaterystore',
            name='name',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='eaterystore',
            name='online_order',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eaterystore',
            name='online_order_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='eaterystore',
            name='payment_accepts_brbs',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eaterystore',
            name='payment_accepts_cash',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eaterystore',
            name='payment_accepts_meal_swipes',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
