# Generated by Django 4.0 on 2022-01-06 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eateries', '0002_alter_eaterystore_campus_area_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitemstore',
            old_name='price',
            new_name='base_price',
        ),
        migrations.CreateModel(
            name='MenuSubItemStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_price', models.FloatField(null=True)),
                ('total_price', models.FloatField(null=True)),
                ('name', models.CharField(max_length=40)),
                ('item_subsection', models.CharField(max_length=40)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='eateries.menuitemstore')),
            ],
        ),
    ]
