# Generated by Django 4.0 on 2022-01-10 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eateries', '0002_closedeventschedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='closedeventschedule',
            name='eatery',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='eateries.eaterystore'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='closedeventschedule',
            name='event_description',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Brunch', 'Brunch'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('General', 'General')], default='hello', max_length=10),
            preserve_default=False,
        ),
    ]
