# Generated by Django 4.0 on 2022-01-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eateries', '0004_alter_menuitemstore_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitemstore',
            name='base_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menusubitemstore',
            name='additional_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menusubitemstore',
            name='total_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
