# Generated by Django 4.0 on 2022-01-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eateries', '0005_alter_menuitemstore_base_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exceptionstore',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='menuitemstore',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
