# Generated by Django 4.0 on 2022-01-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eateries', '0005_dateeventschedule_event_description_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categoryitemassociation',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='categoryitemassociation',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='categorystore',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='closedeventschedule',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dateeventschedule',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dayofweekeventschedule',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='exceptionstore',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='itemstore',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='menustore',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subitemstore',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='categorystore',
            unique_together={('menu', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='menustore',
            unique_together={('eatery', 'name')},
        ),
    ]
