# Generated by Django 4.0 on 2022-01-11 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eateries', '0006_alter_categoryitemassociation_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExceptionStore',
            new_name='AlertStore',
        ),
        migrations.AlterUniqueTogether(
            name='dayofweekeventschedule',
            unique_together={('eatery', 'day_of_week', 'event_description')},
        ),
    ]
