# Generated by Django 4.0 on 2022-03-24 20:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dayofweekeventschedule',
            old_name='end',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='dayofweekeventschedule',
            old_name='start',
            new_name='start_time',
        ),
        migrations.AlterUniqueTogether(
            name='dayofweekeventschedule',
            unique_together={('eatery', 'event_description')},
        ),
        migrations.AddField(
            model_name='dayofweekeventschedule',
            name='offsets',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dayofweekeventschedule',
            name='repeat_interval',
            field=models.IntegerField(default=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dayofweekeventschedule',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='dayofweekeventschedule',
            name='day_of_week',
        ),
    ]
