# Generated by Django 4.0 on 2022-03-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginstore',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
