# Generated by Django 4.0 on 2022-03-24 20:22

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_end_dayofweekeventschedule_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayofweekeventschedule',
            name='offsets',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
