# Generated by Django 4.0 on 2022-03-24 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_dayofweekeventschedule_offsets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dayofweekeventschedule',
            old_name='offsets',
            new_name='offset_lst',
        ),
    ]
