# Generated by Django 4.0 on 2022-03-24 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_offsets_dayofweekeventschedule_offset_lst'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayofweekeventschedule',
            name='offset_lst',
        ),
    ]
