# Generated by Django 4.0 on 2022-03-25 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_dayofweekeventschedule_offset_lst'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DayOfWeekEventSchedule',
            new_name='RepeatingEventSchedule',
        ),
    ]
