# Generated by Django 4.0 on 2022-04-13 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_dayofweekeventschedule_repeatingeventschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleException',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_time', models.DateField(blank=True, null=True)),
                ('end_time', models.DateField(blank=True, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.repeatingeventschedule')),
            ],
        ),
        migrations.RemoveField(
            model_name='dateeventschedule',
            name='eatery',
        ),
        migrations.RemoveField(
            model_name='dateeventschedule',
            name='menu',
        ),
        migrations.DeleteModel(
            name='ClosedEventSchedule',
        ),
        migrations.DeleteModel(
            name='DateEventSchedule',
        ),
    ]
