# Generated by Django 4.0 on 2022-04-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_scheduleexception_remove_dateeventschedule_eatery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleexception',
            name='exception_type',
            field=models.CharField(choices=[('closed', 'Closed'), ('modified', 'Modified')], default='modified', max_length=10),
            preserve_default=False,
        ),
    ]
