# Generated by Django 4.0 on 2022-04-17 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_scheduleexception_exception_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleexception',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheduleexception',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
