# Generated by Django 4.0 on 2022-04-17 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_scheduleexception_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleexception',
            name='eatery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='api.eaterystore'),
            preserve_default=False,
        ),
    ]
