# Generated by Django 4.0 on 2022-04-19 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_scheduleexception_eatery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportstore',
            name='eatery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.eaterystore'),
        ),
    ]
