# Generated by Django 4.0 on 2022-04-23 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eatery', '0001_initial'),
        ('api', '0012_alter_reportstore_eatery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertstore',
            name='eatery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='eatery.eaterystore'),
        ),
        migrations.AlterField(
            model_name='itemstore',
            name='eatery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='eatery.eaterystore'),
        ),
        migrations.AlterField(
            model_name='menustore',
            name='eatery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='eatery.eaterystore'),
        ),
        migrations.AlterField(
            model_name='repeatingeventschedule',
            name='eatery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='eatery.eaterystore'),
        ),
        migrations.AlterField(
            model_name='reportstore',
            name='eatery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='eatery.eaterystore'),
        ),
        migrations.AlterField(
            model_name='scheduleexception',
            name='eatery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='eatery.eaterystore'),
        ),
        migrations.AlterField(
            model_name='transactionhistorystore',
            name='eatery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='eatery.eaterystore'),
        ),
        migrations.DeleteModel(
            name='EateryStore',
        ),
    ]
