# Generated by Django 4.0 on 2023-03-31 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eatery', '0003_alter_eatery_location_alter_eatery_menu_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('netid', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eateries_managed', models.ManyToManyField(related_name='chefs', to='eatery.Eatery')),
            ],
        ),
    ]
