# Generated by Django 4.0 on 2023-03-31 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_item_base_price'),
        ('eatery', '0003_alter_eatery_location_alter_eatery_menu_summary'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.AddField(
            model_name='student',
            name='favorite_eateries',
            field=models.ManyToManyField(related_name='student', to='eatery.Eatery'),
        ),
        migrations.AddField(
            model_name='student',
            name='favorite_items',
            field=models.ManyToManyField(related_name='student', to='item.Item'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='chef',
            name='eateries_managed',
            field=models.ManyToManyField(related_name='chef', to='eatery.Eatery'),
        ),
    ]
