# Generated by Django 4.0 on 2022-11-15 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eatery',
            name='menu_summary',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
    ]
