# Generated by Django 4.0 on 2022-10-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eaterystore',
            name='online_order_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
