# Generated by Django 4.0 on 2023-03-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatery', '0002_alter_eatery_menu_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eatery',
            name='location',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='eatery',
            name='menu_summary',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
